// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.12.4
// source: api/myinvest/account.proto

package myinvest

import (
	empty "github.com/golang/protobuf/ptypes/empty"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserTgId struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TgId int64 `protobuf:"varint,1,opt,name=TgId,proto3" json:"TgId,omitempty"`
}

func (x *UserTgId) Reset() {
	*x = UserTgId{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_myinvest_account_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserTgId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserTgId) ProtoMessage() {}

func (x *UserTgId) ProtoReflect() protoreflect.Message {
	mi := &file_api_myinvest_account_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserTgId.ProtoReflect.Descriptor instead.
func (*UserTgId) Descriptor() ([]byte, []int) {
	return file_api_myinvest_account_proto_rawDescGZIP(), []int{0}
}

func (x *UserTgId) GetTgId() int64 {
	if x != nil {
		return x.TgId
	}
	return 0
}

type TinkoffToken struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserTgId     int64  `protobuf:"varint,1,opt,name=UserTgId,proto3" json:"UserTgId,omitempty"`
	TinkoffToken string `protobuf:"bytes,2,opt,name=TinkoffToken,proto3" json:"TinkoffToken,omitempty"`
}

func (x *TinkoffToken) Reset() {
	*x = TinkoffToken{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_myinvest_account_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TinkoffToken) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TinkoffToken) ProtoMessage() {}

func (x *TinkoffToken) ProtoReflect() protoreflect.Message {
	mi := &file_api_myinvest_account_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TinkoffToken.ProtoReflect.Descriptor instead.
func (*TinkoffToken) Descriptor() ([]byte, []int) {
	return file_api_myinvest_account_proto_rawDescGZIP(), []int{1}
}

func (x *TinkoffToken) GetUserTgId() int64 {
	if x != nil {
		return x.UserTgId
	}
	return 0
}

func (x *TinkoffToken) GetTinkoffToken() string {
	if x != nil {
		return x.TinkoffToken
	}
	return ""
}

type MoneyValue struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Units int64 `protobuf:"varint,1,opt,name=Units,proto3" json:"Units,omitempty"`
	Nano  int32 `protobuf:"varint,2,opt,name=Nano,proto3" json:"Nano,omitempty"`
}

func (x *MoneyValue) Reset() {
	*x = MoneyValue{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_myinvest_account_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MoneyValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoneyValue) ProtoMessage() {}

func (x *MoneyValue) ProtoReflect() protoreflect.Message {
	mi := &file_api_myinvest_account_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoneyValue.ProtoReflect.Descriptor instead.
func (*MoneyValue) Descriptor() ([]byte, []int) {
	return file_api_myinvest_account_proto_rawDescGZIP(), []int{2}
}

func (x *MoneyValue) GetUnits() int64 {
	if x != nil {
		return x.Units
	}
	return 0
}

func (x *MoneyValue) GetNano() int32 {
	if x != nil {
		return x.Nano
	}
	return 0
}

type PayinRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TgId       *UserTgId   `protobuf:"bytes,1,opt,name=TgId,proto3" json:"TgId,omitempty"`
	MoneyValue *MoneyValue `protobuf:"bytes,2,opt,name=MoneyValue,proto3" json:"MoneyValue,omitempty"`
}

func (x *PayinRequest) Reset() {
	*x = PayinRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_myinvest_account_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PayinRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayinRequest) ProtoMessage() {}

func (x *PayinRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_myinvest_account_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayinRequest.ProtoReflect.Descriptor instead.
func (*PayinRequest) Descriptor() ([]byte, []int) {
	return file_api_myinvest_account_proto_rawDescGZIP(), []int{3}
}

func (x *PayinRequest) GetTgId() *UserTgId {
	if x != nil {
		return x.TgId
	}
	return nil
}

func (x *PayinRequest) GetMoneyValue() *MoneyValue {
	if x != nil {
		return x.MoneyValue
	}
	return nil
}

var File_api_myinvest_account_proto protoreflect.FileDescriptor

var file_api_myinvest_account_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x61, 0x70, 0x69, 0x2f, 0x6d, 0x79, 0x69, 0x6e, 0x76, 0x65, 0x73, 0x74, 0x2f, 0x61,
	0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x6d, 0x79,
	0x69, 0x6e, 0x76, 0x65, 0x73, 0x74, 0x5f, 0x61, 0x70, 0x69, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74,
	0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x1e, 0x0a, 0x08, 0x55, 0x73, 0x65, 0x72, 0x54,
	0x67, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x54, 0x67, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x04, 0x54, 0x67, 0x49, 0x64, 0x22, 0x4e, 0x0a, 0x0c, 0x54, 0x69, 0x6e, 0x6b, 0x6f,
	0x66, 0x66, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x55, 0x73, 0x65, 0x72, 0x54,
	0x67, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x55, 0x73, 0x65, 0x72, 0x54,
	0x67, 0x49, 0x64, 0x12, 0x22, 0x0a, 0x0c, 0x54, 0x69, 0x6e, 0x6b, 0x6f, 0x66, 0x66, 0x54, 0x6f,
	0x6b, 0x65, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x54, 0x69, 0x6e, 0x6b, 0x6f,
	0x66, 0x66, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x36, 0x0a, 0x0a, 0x4d, 0x6f, 0x6e, 0x65, 0x79,
	0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x55, 0x6e, 0x69, 0x74, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x55, 0x6e, 0x69, 0x74, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x4e,
	0x61, 0x6e, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x4e, 0x61, 0x6e, 0x6f, 0x22,
	0x74, 0x0a, 0x0c, 0x50, 0x61, 0x79, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x2a, 0x0a, 0x04, 0x54, 0x67, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e,
	0x6d, 0x79, 0x69, 0x6e, 0x76, 0x65, 0x73, 0x74, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x55, 0x73, 0x65,
	0x72, 0x54, 0x67, 0x49, 0x64, 0x52, 0x04, 0x54, 0x67, 0x49, 0x64, 0x12, 0x38, 0x0a, 0x0a, 0x4d,
	0x6f, 0x6e, 0x65, 0x79, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x18, 0x2e, 0x6d, 0x79, 0x69, 0x6e, 0x76, 0x65, 0x73, 0x74, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x4d,
	0x6f, 0x6e, 0x65, 0x79, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x0a, 0x4d, 0x6f, 0x6e, 0x65, 0x79,
	0x56, 0x61, 0x6c, 0x75, 0x65, 0x32, 0x95, 0x01, 0x0a, 0x0c, 0x55, 0x73, 0x65, 0x72, 0x73, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x48, 0x0a, 0x12, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x54, 0x69, 0x6e, 0x6b, 0x6f, 0x66, 0x66, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x1a, 0x2e, 0x6d,
	0x79, 0x69, 0x6e, 0x76, 0x65, 0x73, 0x74, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x54, 0x69, 0x6e, 0x6b,
	0x6f, 0x66, 0x66, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79,
	0x12, 0x3b, 0x0a, 0x05, 0x50, 0x61, 0x79, 0x49, 0x6e, 0x12, 0x1a, 0x2e, 0x6d, 0x79, 0x69, 0x6e,
	0x76, 0x65, 0x73, 0x74, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x50, 0x61, 0x79, 0x69, 0x6e, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x42, 0x39, 0x5a,
	0x37, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x76, 0x61, 0x6c, 0x79,
	0x61, 0x6e, 0x6b, 0x69, 0x6c, 0x79, 0x61, 0x6e, 0x2f, 0x73, 0x61, 0x6e, 0x64, 0x62, 0x6f, 0x78,
	0x2d, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x2d, 0x62, 0x6f, 0x74, 0x2f, 0x61, 0x70, 0x69, 0x2f,
	0x6d, 0x79, 0x69, 0x6e, 0x76, 0x65, 0x73, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_myinvest_account_proto_rawDescOnce sync.Once
	file_api_myinvest_account_proto_rawDescData = file_api_myinvest_account_proto_rawDesc
)

func file_api_myinvest_account_proto_rawDescGZIP() []byte {
	file_api_myinvest_account_proto_rawDescOnce.Do(func() {
		file_api_myinvest_account_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_myinvest_account_proto_rawDescData)
	})
	return file_api_myinvest_account_proto_rawDescData
}

var file_api_myinvest_account_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_api_myinvest_account_proto_goTypes = []interface{}{
	(*UserTgId)(nil),     // 0: myinvest_api.UserTgId
	(*TinkoffToken)(nil), // 1: myinvest_api.TinkoffToken
	(*MoneyValue)(nil),   // 2: myinvest_api.MoneyValue
	(*PayinRequest)(nil), // 3: myinvest_api.PayinRequest
	(*empty.Empty)(nil),  // 4: google.protobuf.Empty
}
var file_api_myinvest_account_proto_depIdxs = []int32{
	0, // 0: myinvest_api.PayinRequest.TgId:type_name -> myinvest_api.UserTgId
	2, // 1: myinvest_api.PayinRequest.MoneyValue:type_name -> myinvest_api.MoneyValue
	1, // 2: myinvest_api.UsersService.UpdateTinkoffToken:input_type -> myinvest_api.TinkoffToken
	3, // 3: myinvest_api.UsersService.PayIn:input_type -> myinvest_api.PayinRequest
	4, // 4: myinvest_api.UsersService.UpdateTinkoffToken:output_type -> google.protobuf.Empty
	4, // 5: myinvest_api.UsersService.PayIn:output_type -> google.protobuf.Empty
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_myinvest_account_proto_init() }
func file_api_myinvest_account_proto_init() {
	if File_api_myinvest_account_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_myinvest_account_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserTgId); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_myinvest_account_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TinkoffToken); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_myinvest_account_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MoneyValue); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_myinvest_account_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PayinRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_myinvest_account_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_myinvest_account_proto_goTypes,
		DependencyIndexes: file_api_myinvest_account_proto_depIdxs,
		MessageInfos:      file_api_myinvest_account_proto_msgTypes,
	}.Build()
	File_api_myinvest_account_proto = out.File
	file_api_myinvest_account_proto_rawDesc = nil
	file_api_myinvest_account_proto_goTypes = nil
	file_api_myinvest_account_proto_depIdxs = nil
}
