telegram:
  token: '<your-telegram-bot-token>'
  getUpdates:
    offset: 0
    limit: 100
    timeout: 0
    allowed_updates: ['message']

tinkoff:
  endpoint: 'invest-public-api.tinkoff.ru:443'
  defaultToken: '<your-sandbox-tinkoff-token>'
  updateTime: 10

rpc:
  host: 'localhost'
  port: '8080'

myinvest:
  host: 'localhost'
  port: '8081'

database:
  host: 'localhost'
  port: '5432'
  username: 'postgres'
  password: 'postgres'
